FROM debian:12-slim as builder

ARG ZTM_VERSION

RUN apt-get update && apt-get install -y curl tar && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /ztm
RUN curl -sL https://github.com/flomesh-io/ztm/releases/download/${ZTM_VERSION}/ztm-aio-${ZTM_VERSION}-generic_linux-x86_64.tar.gz \
    | tar -xz

FROM debian:12-slim

RUN #useradd -m -d /home/ztm ztm
RUN #chown -R ztm:ztm /home/ztm

COPY --from=builder bin/ztm /bin/ztm
RUN chmod +x /bin/ztm

#WORKDIR /home/ztm

#USER ztm